#spring.docker.compose.file[0]=compose-dev.yaml
server.port=9080
spring.data.redis.port=6379
#H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.url=jdbc:h2:mem:embalagens_pamplona;MODE=MySQL;
#logging.level.org.flywaydb=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.pattern.console=%d{yyyy-MM dd HH:mm:ss} %-5level %logger{36} -%msg%n
#forma de criação do banco
spring.jpa.hibernate.ddl-auto=update
#mostrar query
spring.jpa.show-sql=true
#formatar sql
spring.jpa.properties.hibernate.format_sql=true
#formata logs
logging.charset.console=utf-8
spring.jpa.properties.hibernate.show_sql=true
logging.level.org.hibernate.type=trace
spring.sql.init.mode=always
logging.level.org.hibernate.sql=debug
logging.level.org.springframework.web=debug
#email testes - mailtrap.io
#email
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=31b3cae8150bdb
spring.mail.password=abc8dd1a513a40
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.coonnectiontimeout=5000
spring.mail.properties.smtp.timeout=5000
spring.mail.properties.smtp.writeTimeout=5000
spring.mail.properties.mail.smtp.from=sinigagliafernando@gmail.com
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#migrations
#spring.flyway.url=${SPRING_DATASOURCE_URL}
#spring.flyway.schemas=embalagens_pamplona
#spring.flyway.user=${SPRING_DATASOURCE_USERNAME}
#spring.flyway.password=${SPRING_DATASOURCE_PASSWORD}
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration/mysql
#spring.flyway.baseline-version=1
#spring.flyway.baseline-on-migrate=true
#spring.flyway.baselineOnMigrate = true
#swagger
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/docs
springdoc.paths-to-match=/api/**
springdoc.swagger-ui.default-models-expand-depth=1
springdoc.swagger-ui.deep-linking=false
spring.config.import=optional:file:./env
##definindo o diretorio de upload de arquivos
file.upload-dir=/uploads
#definindo como ler os arquivos binarios no server
spring.servlet.multipart.enabled=true
#definindo o tamanho do arquivo qu e será enviado (por exemplo 2kb a partir disso sera armazenado no disco)
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
spring.security.user.name=root
spring.security.user.password=root
spring.jackson.default-property-inclusion=non_empty
jwt.key=hauhauhauhauhauhsudhusahuhsaudsa
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=864000000
security.cookies=true
security.cookiesMaxAge=0
secret.key.crypto=KAJSDHKJASHDJKASHDKAJSHDKJASHDJKASHQWBDWQIDUQWHKDNHUAHSDIJIQO

#stripe
stripe.secret.key=sk_test_51SyX83DPqoh1o2B5ihxC3A8zm4c9R2LMgeL4sVK9lKBQaEWhuaeASFudZxa5MJVfLgb5DfhPu66qznBk4JOr2wDT00mubaXvJs
stripe.endpoint.secret=whsec_5dc67546531e238ab1acef291165ecd2ca9463122fc4628a486bc4a55b263667
spring.jpa.defer-datasource-initialization=true
spring.main.allow-circular-references=true
